### ISSUE TITLE
bug: Inconsistent references annotations.

### ISSUE THREAD

**Issue by enitrat** [starkware-libs/cairo#4221]
# Bug Report

**Cairo version:**
2.3.0-rc0

**Current behavior:**
We needed a `TryIntoResult<T,U,E>` type in Kakarot that tries to convert T into U and throws E if ever it fails.

This trait was implemented as such:

```rust
trait TryIntoResult<T, U, E> {
    fn try_into_result(self: T) -> Result<U, E>;
}
```

Here are two implementations of this trait, for `usize` and `StorageBaseAddress`

```rust

impl U256TryIntoResultU32 of TryIntoResult<u256, usize, EVMError> {
    /// Converts a u256 into a Result<u32, EVMError>
    /// If the u256 is larger than MAX_U32, it returns an error.
    /// Otherwise, it returns the casted value.
    fn try_into_result(self: u256) -> Result<usize, EVMError> {
        match self.try_into() {
            Option::Some(value) => Result::Ok(value),
            Option::None => Result::Err(EVMError::TypeConversionError(TYPE_CONVERSION_ERROR))
        }
    }
}

impl U256TryIntoResultStorageBaseAddress of TryIntoResult<u256, StorageBaseAddress, EVMError> {
    /// Converts a u256 into a Result<u32, EVMError>
    /// If the u256 is larger than MAX_U32, it returns an error.
    /// Otherwise, it returns the casted value.
    fn try_into_result(self: u256) -> Result<StorageBaseAddress, EVMError> {
        let res_felt: felt252 = self
            .try_into()
            .ok_or(EVMError::TypeConversionError(TYPE_CONVERSION_ERROR))?;
        let res_sba: StorageBaseAddress = res_felt
            .try_into()
            .ok_or(EVMError::TypeConversionError(TYPE_CONVERSION_ERROR))?;
        Result::Ok(res_sba)
    }
}
```

The error occurs when running the `pop_usize` functions as defined below.
Both of these syntaxes (which are strictly equivalent) are not throwing any compile-time error. I expect them to be valid and run properly. If not valid, I expect them to throw an error at compile time.

```rust
    #[inline(always)]
    fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
        let item: u256 = self.pop()?;
        let res: Result<usize, EVMError> = item.try_into_result();
        res
    }
```

```rust
    #[inline(always)]
    fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
        let item: u256 = self.pop()?;
        item.try_into_result()
    }
```    

```shell
❯ scarb test -p evm
     Running cairo-test evm
   Compiling test(evm_unittest) evm v0.1.0 (/Users/msaug/temp/kakarot-ssj/crates/evm/Scarb.toml)
    Finished release target(s) in 7 seconds
testing evm ...
Error: Failed setting up runner.

Caused by:
    #467815: Inconsistent references annotations.
```

**Expected behavior:**

Ideally, the syntax used would be supported by the compiler and convert `u256` into `Result<usize, EVMError>`. If not supported, the compiler would catches eventual errors before trying running the tests.

On a side note, I expect the following snipped to be a valid syntax when compiling, and be able to infer types correctly

```rust
    #[inline(always)]
    fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
        let item: u256 = self.pop()?;
        let res:usize = item.try_into_result()?;
        Result::Ok(res)
    }
```

The compile-time error is
```shell
error: Return type "core::result::Result::<core::integer::u32, evm::errors::EVMError>" does not wrap error "?2"
 --> /kakarot-ssj/crates/evm/src/stack.cairo:118:19
        let res:usize = item.try_into_result()?;
```

**Steps to reproduce:**
Unfortunately, after many attempts I have not been able to isolate and reproduce a minimal working example of this bug. 

I can only link a branch of Kakarot where this bug occurs
https://github.com/kkrt-labs/kakarot-ssj/tree/bug-inconsistent-ref

**Related code:**
More specifically, the code occurs when running `scarb cairo-test -p evm`. 
I isolated the cause, which are the `pop_usize` and `pop_sba` methods in the [stack.cairo](https://github.com/kkrt-labs/kakarot-ssj/blob/bug-inconsistent-ref/crates/evm/src/stack.cairo#L116-L119) file.
The `TryIntoResult` trait is defined in the `utils` package, [traits.cairo](https://github.com/kkrt-labs/kakarot-ssj/blob/main/crates/utils/src/traits.cairo#L87-L115) file.

**Other information:**

I tried to reproduce a similar behavior without success. First with a simple example using this traits and a simple error system, then closer to the Kakarot issue by copying the Stack and its culprit methods.
I was unable to reproduce it in another repository.

Interestingly, the following syntax works fine:

```rust
    #[inline(always)]
    fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
        let item: u256 = self.pop()?;
        let res = TryIntoResult::<u256, usize, EVMError>::try_into_result(item)?;
        Result::Ok(res)
    }
```

**Comment by orizi** [comment]
I don't understand what is the specific bug.

**Comment by enitrat** [comment]
> I don't understand what is the specific bug.

Running `scarb cairo-test` failed with an `Inconsistent references annotations` error

```shell
❯ scarb test -p evm
     Running cairo-test evm
   Compiling test(evm_unittest) evm v0.1.0 (/Users/msaug/temp/kakarot-ssj/crates/evm/Scarb.toml)
    Finished release target(s) in 7 seconds
testing evm ...
Error: Failed setting up runner.

Caused by:
    #467815: Inconsistent references annotations.
```

This is not a high-priority issue, and I was not able to reproduce it out of its context. But I just wanted to have it open for the record. 

Given the context introduced in OP, the following functions (equivalent syntax) cause the `Inconsistent references annotations.` error.

```rust

/// variant 1
    #[inline(always)]
    fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
        let item: u256 = self.pop()?;
        let res: Result<usize, EVMError> = item.try_into_result();
        res
    }

/// variant 2
    #[inline(always)]
    fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
        let item: u256 = self.pop()?;
        item.try_into_result()
    }
```

The following, works

```rust
    #[inline(always)]
    fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
        let item: u256 = self.pop()?;
        let res = TryIntoResult::<u256, usize, EVMError>::try_into_result(item)?;
        Result::Ok(res)
    }
```

**Comment by orizi** [comment]
Got it - thanks.

**Comment by orizi** [comment]
Can you please check if this still happens? (on 2.3.1, and on 2.4.0-rc0)
(the inference of `?` works from 2.3.1 and on - i'm talking about the more major issue)

**Comment by enitrat** [comment]
The  `#467815: Inconsistent references annotations.` error still happens on 2.3.1 - I will check when Scarb releases 2.4.0-rc0

**Comment by orizi** [comment]
Pretty sure I found the culprit.
This can only be solved with a starknet update - as it changes the AP change calculation method.
Checking if we can include in Sierra 1.4.0 - otherwise would have to wait for 1.5.0.

**Comment by orizi** [comment]
It seems I managed to include it.
When 2.4.0-rc1 is out - please check :)

**Comment by enitrat** [comment]
Amazing, thank you!

**Comment by orizi** [comment]
Can you please check and close if i'm actually correct and this fixes the issue?

**Comment by enitrat** [comment]
I tested with `2.4.0-rc2`, here are the results:

> On a side note, I expect the following snipped to be a valid syntax when compiling, and be able to infer types correctly
> 
> ```rust
>     #[inline(always)]
>     fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
>         let item: u256 = self.pop()?;
>         let res:usize = item.try_into_result()?;
>         Result::Ok(res)
>     }
> ```
> 
> The compile-time error is
> ```shell
> error: Return type "core::result::Result::<core::integer::u32, evm::errors::EVMError>" does not wrap error "?2"
>  --> /kakarot-ssj/crates/evm/src/stack.cairo:118:19
>         let res:usize = item.try_into_result()?;
> ```

This works now!

However, this one still doesn't work:

> ```rust
>     #[inline(always)]
>     fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
>         let item: u256 = self.pop()?;
>         let res: Result<usize, EVMError> = item.try_into_result();
>         res
>     }
> ```
> 
> ```rust
>     #[inline(always)]
>     fn pop_usize(ref self: Stack) -> Result<usize, EVMError> {
>         let item: u256 = self.pop()?;
>         item.try_into_result()
>     }
> ```    
> 
> ```shell
> ❯ scarb test -p evm
>      Running cairo-test evm
>    Compiling test(evm_unittest) evm v0.1.0 (/Users/msaug/temp/kakarot-ssj/crates/evm/Scarb.toml)
>     Finished release target(s) in 7 seconds
> testing evm ...
> Error: Failed setting up runner.
> 
> Caused by:
>     #467815: Inconsistent references annotations.
> ```

**Comment by orizi** [comment]
Seems to be working now on 2.6.1 and on main :)
